# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.12-stretch-browsers
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - node10-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node10-dependencies-

      - run: npm install
      - run: ./node_modules/.bin/jspm install

      - save_cache:
          paths:
            - node_modules
          key: node10-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: node ./node_modules/gulp/bin/gulp.js build
      - run: node ./node_modules/gulp/bin/gulp.js test
