name: main
on: [push]
env:

jobs:

  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 11
      - run: npm run cut-release
